-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Breeze_Light")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 3,
            size = 6,
        },
        rounding = 20,
        rounding_power = 2.2,
    },
    general = {
        border_size = 2,
        gaps_in = 4,
        gaps_out = 15,
    },
    input = {
        kb_layout = "us,ir",
    },
})


-- Workspaces
hl.workspace_rule({
    workspace = "1",
    persistent = true,
})
hl.workspace_rule({
    workspace = "2",
    persistent = true,
})
hl.workspace_rule({
    workspace = "3",
    persistent = true,
})
hl.workspace_rule({
    workspace = "4",
    persistent = true,
})
hl.workspace_rule({
    workspace = "5",
    persistent = true,
})
hl.workspace_rule({
    workspace = "6",
    persistent = true,
})
hl.workspace_rule({
    workspace = "7",
    persistent = true,
})
hl.workspace_rule({
    workspace = "8",
    persistent = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia")
end)
